### ISSUE TITLE
One lines?

### ISSUE THREAD

**Issue by Magneticdud** [Magneticdud/Hitomi-fansub#6]
Maybe it's better if i do all the subs in one line, then it's the player that it has to split in half if there isn't enough space?

**Comment by Magneticdud** [comment]
I converted episode 51 to one lines in commit 491fdc6b4d77445a29ca40d41eef8a12f87f0308

**Comment by MBjdrma** [comment]
HI! I found this when I finished watching through Ep 155 (raws) and realized that Ep 156 hasn't been posted anywhere...I would gladly work on the missing subtitles if you are still hosting this project. I didn't realize so much of the process is automated! I understand enough Japanese to correct the typos and probably many errors in translation. I'm not clear about some of your other instructions - let me know if/how I can help!

**Comment by Magneticdud** [comment]
Sure i am still doing this project, just i don't have much time...

If you want to help, i can teach you how to do so we can collaborate

**Comment by MBjdrma** [comment]
I understand! I really appreciate all subbers and want to give some of my time to help out. I loved this drama, too. Yes, please help me get into the episodes to edit the typos, then how to save the work. I will do in one lines if that's your preference, fine with me.

**Comment by MBjdrma** [comment]
Since I'm not planning to start my own projects, I didn't know if I should do the whole "Hello World" instructions? If you think a good first step, I'll do it.

**Comment by Magneticdud** [comment]
I can give you account "write" permissions to this project

basically it works like this:

https://www.youtube.com/watch?v=GwsJ_eudbGM

 later I'll write a basic tutorial on how to use github for this, and how to use the subtitles editor (aegisub)

**Comment by Magneticdud** [comment]
Once you have editing permissions, is very easy, press the edit button:

![step1](https://user-images.githubusercontent.com/2940598/57371353-cf624a80-7192-11e9-801e-f912067531b2.png)

then do the edits (or copy/paste from another program like aegisub):

![step2](https://user-images.githubusercontent.com/2940598/57371378-e3a64780-7192-11e9-8be8-859a9bd7e726.png)

then on the bottom of the page press "commit" which is equivalent to "save".

![step3](https://user-images.githubusercontent.com/2940598/57371445-08022400-7193-11e9-95c5-08a36cc0f23f.png)

The description is optional and it's only for future reference, know what you changed:

For example, the small edit i did is available as commit 1478a and everyone can see what i changed:

![step4](https://user-images.githubusercontent.com/2940598/57371495-2b2cd380-7193-11e9-89f8-42d3b6febb43.png)

**Comment by MBjdrma** [comment]
Thank you! It will take me a moment to review and try this out -- over the weekend I plan to. I'll make sure I'm doing it right before I make a mess out of it!
So you don't actually check the subs against the language in the drama, you are mostly cleaning up the subs produced automatically by an app or program?

**Comment by Magneticdud** [comment]
usually i watch the video in aegisub, which is a "notepad editor" which can let you edit line by line while the audio is flowing

the flow is this:
An user named "Avallach" makes the subs automatically using a program. Since they're automatically written, there are A LOT of errors, so the boring part is that basically each sentence has an error...

Otherwise, if those automated subs aren't automated, they could be based on japanese or chinese subs: the hardest (most boring) part of the subs is to sync the voice to the text: if it can be done automatically it's much better. Aegisubs lets you do the subvtiming manually if that's missing. For example in the youtube video i posted before, I manually did the timing because the automatically generated ones were too corrupted

**Comment by MBjdrma** [comment]
Wow this is a whole new world for me. Aegisub looks amazing. How do I watch in aegisub? I downloaded and opened the program.
Do I understand this correctly? If you watch while in aegisub, the automated (but error filled) subs show up in the box, so you can fix typos + language errors while the drama is playing, plus you can see if they line up with the speaking...yes?
Also, I'm sorry I don't speak Italian! I watched the youtube video a bit but can't get a lot from it. My languages are English, Spanish, Japanese (not fluent)...

**Comment by MBjdrma** [comment]
So, I worked on editing the subs for ep 53 in GitHub, watching the video in a separate window (I watch streaming online). going back and forth btwn that and the GitHub window is pretty awkward but do-able. YES there are so many errors - sometimes so much that there's basically nothing to build off of!

**Comment by MBjdrma** [comment]
What's "soft wrap"?
To make one-line subs, I was deleting the lower of 2 lines. In the example you shared, it looks like you also deleted the lower line, but my version doesn't show the before/after. Will that show up after I save the changes? I am guessing yes (and crossing my fingers).

**Comment by MBjdrma** [comment]
The timing - sometimes it seems OK, but then gets "off" - I didn't do anything about that yet.

**Comment by Magneticdud** [comment]
The timing is a bit hard, it must be manually adjusted with aegisub -  later i do it

**Comment by MBjdrma** [comment]
See my comment on one of my commits for ep53 - before I do any more.

**Comment by Magneticdud** [comment]
Sorry yesterday i was away from the PC. I am checking the files now

Meanwhile take this:

https://wetransfer.com/downloads/5f3902836c7e29512df3e40b79f96caf20190513080701/304a548c358c4386e2b89475a3f3a83c20190513080701/e23ff3

(this comment will be deleted in 24 hours)

**Comment by MBjdrma** [comment]
THANKS - I got the video and see how to open in aegisub - can't try more till later. My work is urban farming and we actually have a few non-rainy days! It's been cold and wet here (Chicago, IL).

**Comment by Magneticdud** [comment]
The subs have been published on d-addicts!

The community did not like "one lines" - saying in some cases the video playing software makes the text too small or too "off the center" to read easily... so... "issue" closed...

**Comment by MBjdrma** [comment]
ah, ok. so, don't turn them into one-lines...did you have to go back and add lines for all of those eps?

To reduce extra characters on a given line, I sometimes bump a word to the next line - is that OK to do?

**Comment by Magneticdud** [comment]
ok to bump

no, someone else on d-addicts added the lines back
